Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "tdnlabs.tradein.net.br"
    config.vm.network "forwarded_port", guest: 80, host: 8899
  #config.vm.network = "private_network", type: "dhcp"

  config.vm.provision :puppet do |puppet|
  	puppet.manifests_path = "puppet/manifests"
  	puppet.manifest_file = "site.pp"
  	puppet.module_path = "puppet/modules"
  end
  
end

